services:
  app:
    build: .
    container_name: madhuri-23a91a0510-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./encrypted_seed.txt:/app/encrypted_seed.txt
    restart: unless-stopped
